#!/bin/sh

. /etc/openwrt_release

feeds_file="/etc/opkg/librerouterfeeds.conf"

[ -f "$feeds_file" ] && {
  echo "LibreRouter opkg feeds already defined - skipping"
  exit 0
}

[ -z "$DISTRIB_TARGET" ] && {
  echo "Release information not available, skipping opkg configuration"
  exit 0
}

if printf '%s' "$DISTRIB_RELEASE" | grep -q SNAPSHOT; then
  echo "Not configuring LibreRouter feed as it is a development built"
else
  base_url="http://repo.librerouter.org/releases/$DISTRIB_RELEASE/targets/$DISTRIB_TARGET/packages"
  echo "Configuring official LibreRouter opkg feeds"
  echo "src/gz librerouter $base_url" > /etc/opkg/librerouterfeeds.conf
fi
